baseURL = "https://edoaltamura.github.io/"
languageCode = "en-us"
title = "Edoardo Altamura"
theme = "hugo-initio"
publishDir = "docs"

[params]
    name = "  Edoardo Altamura  "
    description = "Ph.D. student in Computational Astrophysics and Cosmology"
    email = "edoardo.altamura@student.manchester.ac.uk"
    phone = "+44 (0) 7561 598515"
    address = "Jodrell Bank Centre for Astrophysics, Alan Turing Building, Oxford Road, Manchester M13 9PL, United Kingdom "
    year = 2019
    avatar = "images/profile.png"
    background = ""
    favicon = "images/icon.png"
    DateForm = ""

    showSubheader = true
    showServices = false
    showRecentWorks = true
    showDownload = false
    showClients = false

    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = false
    footerEnableFormWidget = false

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1




[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "12"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/edoardo.altamura"
    icon = "fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/edoaltamura"
    icon = "fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/edo.altamura"
    icon = "fa-instagram"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "google+"
	url = "https://plus.google.com/+nickname"
    icon = "fa-google-plus-square"
    footer = false
    sharethis = true
    network = "googleplus"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/edoardoaltamura"
    icon = "fa-linkedin-square"
    footer = true
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "tumblr"
	url = "https://nickname.tumblr.com"
    icon = "fa-tumblr-square"
    footer = false
    sharethis = false
    network = "tumblr"
[[params.social]]
	title = "github"
	url = "https://github.com/edoaltamura"
    icon = "fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:edoardo.altamura@hotmail.it"
    icon = "fa-envelope"
    footer = true
    sharethis = true
    network = "email"
